# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f48a333cc5ae965f38ec3f98f7efd35346a4a7da888ff237cec258ccab72e3945739973079bbc9b54f233aecb1dd1cd176fce6d49e316856b025553ab0d323

test:
  secret_key_base: 5b6d318474ffc9f8d0b9c21e8b2dab2dd768281bb64548d957c194d5715dc294a37355322b1e098e5f4e7925a21f719a59ba24454263630b1ea64e3b51f934f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
